# environment.yml

# User's minimal environment for hklpy2

# conda env create -f environment.yml
# micromamba create -n hklpy2 -f environment.yml

name: hklpy2

channels:
  - conda-forge  # must come before defaults (for gsl version)
  - defaults

dependencies:
  - python >=3.10,<3.13
  - hkl
  - numpy
  - ophyd
  - packaging
  - pint
  - pip
  - pygobject
